import { expect, test } from '@playwright/test'
import {
  closeListSettings, createList, createTask, listAction, login, logout, openTaskEditor,
  register, resetServer, serverState, taskItem, uniqueEmail,
} from './support/helpers'
import * as mobile from './support/mobile'

test.beforeEach(async ({ request }) => { await resetServer(request) })

async function selectList(page: Parameters<typeof createList>[0], name: string) {
  await closeListSettings(page)
  await page.getByRole('complementary', { name: 'Listen' }).getByRole('button', { name, exact: true }).click()
  await expect(page.getByTestId('list-title')).toHaveText(name)
}

test('Entwürfe für Aufgaben und Listennamen bleiben beim richtigen Listenwechsel', async ({ page }) => {
  await register(page, uniqueEmail('draft-lists'))
  await createList(page, 'Einkaufen')
  await createList(page, 'Arbeit')
  await selectList(page, 'Einkaufen')
  await page.getByRole('textbox', { name: 'Neue Aufgabe', exact: true }).fill('Milch')
  await listAction(page, 'Umbenennen')
  await page.getByLabel('Neuer Listenname').fill('Einkauf am Samstag')
  await selectList(page, 'Arbeit')
  await expect(page.getByRole('textbox', { name: 'Neue Aufgabe', exact: true })).toHaveValue('')
  await expect(page.getByRole('form', { name: 'Liste umbenennen' })).toBeHidden()
  await listAction(page, 'Umbenennen')
  await expect(page.getByLabel('Neuer Listenname')).toHaveValue('Arbeit')
  await page.getByRole('form', { name: 'Liste umbenennen' }).getByRole('button', { name: 'Abbrechen' }).click()
  await selectList(page, 'Einkaufen')
  await expect(page.getByRole('textbox', { name: 'Neue Aufgabe', exact: true })).toHaveValue('Milch')
  await listAction(page, 'Umbenennen')
  await expect(page.getByLabel('Neuer Listenname')).toHaveValue('Einkauf am Samstag')
  await page.getByRole('form', { name: 'Liste umbenennen' }).getByRole('button', { name: 'Speichern' }).click()
  await expect(page.getByRole('dialog', { name: 'Liste verwalten', exact: true })).toBeHidden()
  await expect(page.getByTestId('list-title')).toHaveText('Einkauf am Samstag')
  await page.getByRole('button', { name: 'Hinzufügen', exact: true }).click()
  await expect(taskItem(page, 'Milch')).toBeVisible()
  await selectList(page, 'Arbeit')
  await expect(page.getByText('Noch keine Aufgaben in dieser Liste.')).toBeVisible()
})

test('ein neuer Entwurf überlebt Ansichtswechsel und bewusstes Behalten auf dem Telefon', async ({ page }, info) => {
  await register(page, uniqueEmail('draft-width'))
  await createList(page, 'Einkaufen')
  await page.getByRole('textbox', { name: 'Neue Aufgabe', exact: true }).fill('Milch')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Neue Aufgabe', exact: true }).click()
  await expect(page.getByLabel('Titel', { exact: true })).toHaveValue('Milch')
  await page.getByLabel('Beschreibung (optional)').fill('Zwei Packungen')
  await page.screenshot({ path: info.outputPath('draft-phone.png') })
  await page.getByRole('button', { name: 'Schließen', exact: true }).click()
  await page.getByRole('button', { name: 'Entwurf behalten', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Neue Aufgabe', exact: true })).toBeHidden()
  await mobile.createList(page, 'Arbeit')
  await mobile.openMenu(page)
  await page.getByRole('dialog', { name: 'Menü' }).getByRole('button', { name: 'Einkaufen', exact: true }).click()
  await page.getByRole('button', { name: 'Neue Aufgabe', exact: true }).click()
  await expect(page.getByLabel('Titel', { exact: true })).toHaveValue('Milch')
  await expect(page.getByLabel('Beschreibung (optional)')).toHaveValue('Zwei Packungen')
  await page.setViewportSize({ width: 1280, height: 800 })
  const editor = page.getByRole('dialog', { name: 'Neue Aufgabe', exact: true })
  await expect(editor).toBeVisible()
  await expect(editor.getByLabel('Titel', { exact: true })).toHaveValue('Milch')
  await editor.getByRole('button', { name: 'Speichern', exact: true }).click()
  await expect(taskItem(page, 'Milch')).toContainText('Zwei Packungen')
})

test('Bearbeitungsentwurf überlebt den Ansichtswechsel; Verwerfen entfernt ihn', async ({ page }, info) => {
  await register(page, uniqueEmail('draft-edit'))
  await createList(page, 'Einkaufen')
  await createTask(page, 'Milch')
  await openTaskEditor(page, 'Milch')
  await page.getByLabel('Titel', { exact: true }).fill('Milch und Brot')
  await page.setViewportSize({ width: 740, height: 360 })
  await expect(page.getByRole('dialog', { name: 'Aufgabe', exact: true })).toBeVisible()
  await expect(page.getByLabel('Titel', { exact: true })).toHaveValue('Milch und Brot')
  await page.getByRole('button', { name: 'Schließen', exact: true }).click()
  await expect(page.getByRole('alertdialog')).toBeVisible()
  await page.screenshot({ path: info.outputPath('draft-landscape.png') })
  await page.getByRole('button', { name: 'Verwerfen', exact: true }).click()
  await page.setViewportSize({ width: 1280, height: 800 })
  await openTaskEditor(page, 'Milch')
  await expect(page.getByLabel('Titel', { exact: true })).toHaveValue('Milch')
})

test('gleichzeitige Gerätebearbeitung erhält andere Felder und zeigt echte Feldkonflikte in beiden Ansichten', async ({ page, browser, request }, info) => {
  const email = uniqueEmail('draft-conflict')
  await register(page, email)
  await createList(page, 'Projekt')
  await createTask(page, 'Ausgangslage')
  await expect.poll(async () => (await serverState(request)).tasks.length).toBe(1)
  const second = await browser.newContext()
  try {
    const other = await second.newPage()
    await login(other, email)
    await selectList(other, 'Projekt')
    await expect(taskItem(other, 'Ausgangslage')).toBeVisible()
    await openTaskEditor(page, 'Ausgangslage')
    await page.getByLabel('Titel', { exact: true }).fill('Mein Titel')
    await openTaskEditor(other, 'Ausgangslage')
    await other.getByLabel('Beschreibung (optional)').fill('Andere Notiz')
    await other.getByRole('form', { name: /^Aufgabe bearbeiten:/ }).getByRole('button', { name: 'Speichern', exact: true }).click()
    await expect.poll(async () => (await serverState(request)).tasks[0]?.description).toBe('Andere Notiz')
    await page.getByRole('dialog', { name: 'Aufgabe', exact: true }).getByRole('button', { name: 'Jetzt synchronisieren', exact: true }).click()
    await page.getByRole('form', { name: /^Aufgabe bearbeiten:/ }).getByRole('button', { name: 'Speichern', exact: true }).click()
    await expect(taskItem(page, 'Mein Titel')).toContainText('Andere Notiz')
    await expect.poll(async () => (await serverState(request)).tasks[0]?.title).toBe('Mein Titel')

    await openTaskEditor(page, 'Mein Titel')
    await page.getByLabel('Titel', { exact: true }).fill('Mein nächster Entwurf')
    await other.getByRole('button', { name: 'Jetzt synchronisieren', exact: true }).click()
    await expect(taskItem(other, 'Mein Titel')).toBeVisible()
    await openTaskEditor(other, 'Mein Titel')
    await other.getByLabel('Titel', { exact: true }).fill('Andere Titeländerung')
    await other.getByRole('form', { name: /^Aufgabe bearbeiten:/ }).getByRole('button', { name: 'Speichern', exact: true }).click()
    await expect(other.getByRole('dialog', { name: 'Aufgabe', exact: true })).toBeHidden()
    await expect.poll(async () => (await serverState(request)).tasks[0]?.title).toBe('Andere Titeländerung')
    await page.getByRole('dialog', { name: 'Aufgabe', exact: true }).getByRole('button', { name: 'Jetzt synchronisieren', exact: true }).click()
    await page.getByRole('form', { name: /^Aufgabe bearbeiten:/ }).getByRole('button', { name: 'Speichern', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('inzwischen geändert')
    await expect(page.getByLabel('Titel', { exact: true })).toHaveValue('Mein nächster Entwurf')
    expect((await serverState(request)).tasks[0]?.title).toBe('Andere Titeländerung')
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(page.getByRole('dialog', { name: 'Aufgabe', exact: true })).toBeVisible()
    await expect(page.getByRole('alert')).toContainText('inzwischen geändert')
    await expect(page.getByLabel('Titel', { exact: true })).toHaveValue('Mein nächster Entwurf')
    await page.screenshot({ path: info.outputPath('conflict-phone.png') })
    await page.getByRole('button', { name: 'Aktuellen Stand laden', exact: true }).click()
    await expect(page.getByLabel('Titel', { exact: true })).toHaveValue('Andere Titeländerung')
    await expect(page.getByRole('alert')).toBeHidden()
  } finally { await second.close() }
})

test('Abmelden beendet die Entwurfssitzung', async ({ page }) => {
  const email = uniqueEmail('draft-signout')
  await register(page, email)
  await createList(page, 'Einkaufen')
  await page.getByRole('textbox', { name: 'Neue Aufgabe', exact: true }).fill('Nicht gespeichert')
  await logout(page)
  await login(page, email)
  await selectList(page, 'Einkaufen')
  await expect(page.getByTestId('list-title')).toHaveText('Einkaufen')
  await expect(page.getByRole('textbox', { name: 'Neue Aufgabe', exact: true })).toHaveValue('')
})
