import { expect, test } from '@playwright/test'
import * as desktop from './support/helpers'
import * as phone from './support/mobile'
import { openOverview, overviewSettings } from './support/overview'

for (const mobile of [false, true]) test.describe(mobile ? 'Gesamtansicht Telefon' : 'Gesamtansicht breit', () => {
  test.use({ viewport: mobile ? { width: 390, height: 844 } : { width: 1280, height: 800 }, hasTouch: mobile })
  test.beforeEach(async ({ request }) => { await desktop.resetServer(request) })
  const register = mobile ? phone.register : desktop.register
  const createList = mobile ? phone.createList : desktop.createList
  const createTask = mobile ? phone.createTask : desktop.createTask

  test('beide Sortierungen behalten Herkunft und bestehende Listenreihenfolge', async ({ page }) => {
    await register(page, desktop.uniqueEmail('overview-order'))
    await createList(page, 'Arbeit')
    await createTask(page, 'Ältere Arbeit')
    await createTask(page, 'Neuere Arbeit')
    await createList(page, 'Einkaufen')
    await createTask(page, 'Neuester Einkauf')
    await openOverview(page, mobile)
    await expect(page.getByTestId('overview-task')).toHaveCount(0)
    const settings = await overviewSettings(page)
    await settings.getByLabel('Arbeit', { exact: true }).check()
    await expect(settings.getByLabel('Arbeit', { exact: true })).toBeEnabled()
    await settings.getByLabel('Einkaufen', { exact: true }).check()
    await expect(settings.getByLabel('Einkaufen', { exact: true })).toBeEnabled()
    await settings.getByRole('button', { name: 'Schließen', exact: true }).click()
    await expect(page.getByTestId('overview-task')).toHaveText([/Neuere Arbeit/, /Ältere Arbeit/, /Neuester Einkauf/])
    await page.getByLabel('Ansicht der Gesamtansicht').selectOption('newest')
    await expect(page.getByTestId('overview-task')).toHaveText([/Neuester Einkauf.*Einkaufen/s, /Neuere Arbeit.*Arbeit/s, /Ältere Arbeit.*Arbeit/s])
    await page.getByLabel('Ansicht der Gesamtansicht').selectOption('by_list')
    await expect(page.getByTestId('overview-task')).toHaveText([/Neuere Arbeit/, /Ältere Arbeit/, /Neuester Einkauf/])
  })

  test('Erstellen verlangt eine Zielliste, bis eine Standardliste ausdrücklich gesetzt ist', async ({ page, request }) => {
    await register(page, desktop.uniqueEmail('overview-target'))
    await createList(page, 'Arbeit')
    await openOverview(page, mobile)
    await page.getByRole('button', { name: 'Neue Aufgabe', exact: true }).click()
    const target = page.getByRole('dialog', { name: 'Zielliste wählen' })
    await expect(target.getByLabel('Zielliste', { exact: true })).toHaveValue('')
    await expect(target.getByRole('button', { name: 'Weiter' })).toBeDisabled()
    await target.getByLabel('Zielliste', { exact: true }).selectOption({ label: 'Arbeit' })
    await expect(target).toContainText('ist nicht in der Gesamtansicht')
    await target.getByRole('button', { name: 'Weiter' }).click()
    const editor = page.getByRole('dialog', { name: 'Neue Aufgabe', exact: true })
    await expect(editor).toContainText('Liste: Arbeit')
    await editor.getByLabel('Titel', { exact: true }).fill('Bewusst ausgeschlossene Aufgabe')
    await editor.getByRole('button', { name: 'Speichern', exact: true }).click()
    await expect(editor).toBeHidden()
    await expect.poll(async () => (await desktop.serverState(request)).tasks.map(task => task.title)).toEqual(['Bewusst ausgeschlossene Aufgabe'])
    await expect(page.getByTestId('overview-task')).toHaveCount(0)
    await page.getByRole('button', { name: 'Neue Aufgabe', exact: true }).click()
    await expect(target.getByLabel('Zielliste', { exact: true })).toHaveValue('')
    await target.getByRole('button', { name: 'Schließen', exact: true }).click()
    const settings = await overviewSettings(page)
    await settings.getByLabel('Standardliste für neue Aufgaben').selectOption({ label: 'Arbeit' })
    await expect(settings.getByLabel('Standardliste für neue Aufgaben')).not.toHaveValue('')
    await settings.getByRole('button', { name: 'Schließen', exact: true }).click()
    await page.getByRole('button', { name: 'Neue Aufgabe', exact: true }).click()
    await expect(editor).toContainText('Liste: Arbeit')
    await expect(target).toBeHidden()
    await editor.getByRole('button', { name: 'Zielliste ändern', exact: true }).click()
    await expect(target).toBeVisible()
    await expect(target.getByLabel('Zielliste', { exact: true })).not.toHaveValue('')
  })

  test('merkt die bevorzugte Ansicht nach Neustart und auf einem zweiten Gerät', async ({ page, browser, request }) => {
    const email = desktop.uniqueEmail('overview-remember')
    await register(page, email)
    await createList(page, 'Arbeit')
    await openOverview(page, mobile)
    await expect(page.getByLabel('Ansicht der Gesamtansicht')).toHaveValue('by_list')
    const settings = await overviewSettings(page)
    await settings.getByLabel('Arbeit', { exact: true }).check()
    await expect(settings.getByLabel('Arbeit', { exact: true })).toBeEnabled()
    await settings.getByLabel('Standardliste für neue Aufgaben').selectOption({ label: 'Arbeit' })
    await expect(settings.getByLabel('Standardliste für neue Aufgaben')).not.toHaveValue('')
    await settings.getByRole('button', { name: 'Schließen', exact: true }).click()
    await page.getByLabel('Ansicht der Gesamtansicht').selectOption('newest')
    await expect.poll(async () => (await desktop.serverState(request)).userPreferences[0]?.overview_mode).toBe('newest')
    await page.reload()
    await expect(page.getByLabel('Ansicht der Gesamtansicht')).toHaveValue('newest')
    const otherContext = await browser.newContext({ viewport: { width: 1280, height: 800 }, hasTouch: false })
    try {
      const other = await otherContext.newPage()
      await desktop.login(other, email)
      await expect(other.getByLabel('Ansicht der Gesamtansicht')).toHaveValue('newest')
      const otherSettings = await overviewSettings(other)
      await expect(otherSettings.getByLabel('Arbeit', { exact: true })).toBeChecked()
      await expect(otherSettings.getByLabel('Standardliste für neue Aufgaben')).not.toHaveValue('')
    } finally { await otherContext.close() }
  })

  test('gleiche Titel bearbeiten die richtige Aufgabe; Editor und Entwurf überleben Breitenwechsel', async ({ page, request }, info) => {
    await register(page, desktop.uniqueEmail('overview-editor'))
    await createList(page, 'Arbeit')
    await createTask(page, 'Gleicher Titel')
    await createList(page, 'Einkaufen')
    await createTask(page, 'Gleicher Titel')
    await openOverview(page, mobile)
    const settings = await overviewSettings(page)
    for (const list of ['Arbeit', 'Einkaufen']) {
      await settings.getByLabel(list, { exact: true }).check()
      await expect(settings.getByLabel(list, { exact: true })).toBeEnabled()
    }
    await settings.getByRole('button', { name: 'Schließen', exact: true }).click()
    await page.getByRole('region', { name: 'Aufgaben aus Einkaufen' }).getByRole('button', { name: 'Gleicher Titel', exact: true }).click()
    const editor = page.getByRole('dialog', { name: 'Aufgabe', exact: true })
    await editor.getByLabel('Titel', { exact: true }).fill('Nur Einkauf geändert')
    await page.setViewportSize({ width: mobile ? 1280 : 390, height: mobile ? 800 : 844 })
    await expect(editor.getByLabel('Titel', { exact: true })).toHaveValue('Nur Einkauf geändert')
    await editor.getByRole('button', { name: 'Speichern', exact: true }).click()
    await expect(editor).toBeHidden()
    await expect.poll(async () => (await desktop.serverState(request)).tasks.map(task => task.title).sort()).toEqual(['Gleicher Titel', 'Nur Einkauf geändert'])
    await page.setViewportSize({ width: 390, height: 844 })
    await page.screenshot({ path: info.outputPath('overview-phone.png') })
    await page.setViewportSize({ width: 740, height: 360 })
    await page.screenshot({ path: info.outputPath('overview-landscape.png') })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  })
})
