import { expect, test } from '@playwright/test'
import * as desktop from './support/helpers'
import * as phone from './support/mobile'
import { openOverview, overviewSettings } from './support/overview'

for (const mobile of [false, true]) test.describe(mobile ? 'Neue Kernoberfläche Telefon' : 'Neue Kernoberfläche breit', () => {
  test.use({ viewport: mobile ? { width: 390, height: 844 } : { width: 1280, height: 800 }, hasTouch: mobile })
  test.beforeEach(async ({ request }) => desktop.resetServer(request))

  test('Editor bleibt offen, bewahrt den Entwurf und sperrt den Hintergrund beim Breitenwechsel', async ({ page }, info) => {
    await (mobile ? phone.register : desktop.register)(page, desktop.uniqueEmail('ui-editor'))
    await (mobile ? phone.createList : desktop.createList)(page, 'Arbeit')
    await (mobile ? phone.createTask : desktop.createTask)(page, 'Eine Aufgabe mit einem längeren Titel für den gemeinsamen Editor')
    const editor = await desktop.openTaskEditor(page, 'Eine Aufgabe mit einem längeren Titel für den gemeinsamen Editor')
    await editor.getByLabel('Beschreibung (optional)').fill('Ein Entwurf, der beim Wechsel erhalten bleibt.')
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(editor).toBeVisible()
    await expect(editor.getByLabel('Beschreibung (optional)')).toHaveValue('Ein Entwurf, der beim Wechsel erhalten bleibt.')
    await page.screenshot({ path: info.outputPath('editor-phone.png') })
    await page.setViewportSize({ width: 740, height: 360 })
    await expect(editor.getByRole('button', { name: 'Speichern', exact: true })).toBeInViewport()
    await page.screenshot({ path: info.outputPath('editor-landscape.png') })
    await page.setViewportSize({ width: 1280, height: 800 })
    const background = page.getByRole('complementary', { name: 'Listen', includeHidden: true }).getByRole('button', { name: 'Arbeit', exact: true, includeHidden: true })
    await background.evaluate(node => node.focus())
    expect(await editor.evaluate(node => node.contains(document.activeElement))).toBe(true)
    await editor.getByLabel('Titel', { exact: true }).focus()
    for (let i = 0; i < 16; i += 1) {
      await page.keyboard.press('Tab')
      expect(await editor.evaluate(node => node.contains(document.activeElement))).toBe(true)
    }
    await page.screenshot({ path: info.outputPath('editor-desktop.png') })
    await editor.getByRole('button', { name: 'Speichern', exact: true }).click()
    await expect(editor).toBeHidden()
    await expect(desktop.taskItem(page, 'Eine Aufgabe mit einem längeren Titel für den gemeinsamen Editor')).toContainText('Ein Entwurf')
    await expect(desktop.taskItem(page, 'Eine Aufgabe mit einem längeren Titel für den gemeinsamen Editor').getByRole('button', { name: 'Bearbeiten' })).toBeFocused()
  })

  test('Reihenfolge lässt sich ohne Ziehen ändern; der Editorentwurf bleibt erhalten', async ({ page }) => {
    await (mobile ? phone.register : desktop.register)(page, desktop.uniqueEmail('ui-order'))
    await (mobile ? phone.createList : desktop.createList)(page, 'Einkaufen')
    for (const name of ['Milch', 'Brot', 'Kaffee']) await (mobile ? phone.createTask : desktop.createTask)(page, name)
    const editor = await desktop.openTaskEditor(page, 'Milch')
    await editor.getByLabel('Beschreibung (optional)').fill('Ohne Zucker')
    await editor.getByRole('button', { name: 'Reihenfolge ändern' }).click()
    const order = page.getByRole('dialog', { name: 'Reihenfolge ändern' })
    await order.getByLabel('Einfügen vor').selectOption({ label: 'Kaffee' })
    await order.getByRole('button', { name: 'Position übernehmen' }).click()
    await expect(order).toBeHidden()
    await expect(editor.getByLabel('Beschreibung (optional)')).toHaveValue('Ohne Zucker')
    await editor.getByRole('button', { name: 'Speichern', exact: true }).click()
    const labels = page.getByTestId('task-list').getByRole('checkbox')
    await expect(labels.nth(0)).toHaveAttribute('aria-label', 'Aufgabe erledigen: Milch')
    await expect(labels.nth(1)).toHaveAttribute('aria-label', 'Aufgabe erledigen: Kaffee')
    await expect(labels.nth(2)).toHaveAttribute('aria-label', 'Aufgabe erledigen: Brot')
  })

  test('Abgehakte Aufgaben bleiben im Editor erreichbar und lassen sich erledigt verschieben', async ({ page, request }) => {
    await (mobile ? phone.register : desktop.register)(page, desktop.uniqueEmail('ui-completed'))
    await (mobile ? phone.createList : desktop.createList)(page, 'Quelle')
    await (mobile ? phone.createTask : desktop.createTask)(page, 'Beleg aufbewahren')
    let editor = await desktop.openTaskEditor(page, 'Beleg aufbewahren')
    await editor.getByLabel('Beschreibung (optional)').fill('Die gespeicherten Einzelheiten bleiben erreichbar.')
    await editor.getByRole('button', { name: 'Speichern', exact: true }).click()
    await expect(editor).toBeHidden()
    const settings = await desktop.openListSettings(page)
    await settings.getByLabel('Abgehakt am Listenende').check()
    await desktop.closeListSettings(page)
    await (mobile ? phone.createList : desktop.createList)(page, 'Ziel')
    if (mobile) {
      await phone.openMenu(page)
      await page.getByRole('dialog', { name: 'Menü' }).getByRole('button', { name: 'Quelle', exact: true }).click()
    } else await desktop.selectList(page, 'Quelle')
    await page.getByRole('checkbox', { name: 'Aufgabe erledigen: Beleg aufbewahren' }).click()
    const completed = page.getByRole('region', { name: 'Abgehakt', exact: true })
    await completed.getByRole('button', { name: /^Abgehakt/i }).click()
    await completed.getByRole('button', { name: 'Aufgabe bearbeiten: Beleg aufbewahren', exact: true }).click()
    editor = page.getByRole('dialog', { name: 'Aufgabe', exact: true })
    await expect(editor.getByLabel('Beschreibung (optional)')).toHaveValue('Die gespeicherten Einzelheiten bleiben erreichbar.')
    await expect(editor.getByRole('button', { name: 'Als offen markieren', exact: true })).toBeVisible()
    await editor.getByRole('button', { name: 'In andere Liste verschieben' }).click()
    const move = page.getByRole('dialog', { name: 'Aufgabe verschieben' })
    await move.getByRole('button', { name: 'Ziel', exact: true }).click()
    await move.getByRole('button', { name: 'Verschieben', exact: true }).click()
    await expect(editor).toBeHidden()
    await expect.poll(async () => {
      const state = await desktop.serverState(request)
      const row = state.tasks.find(task => task.title === 'Beleg aufbewahren')
      return row?.completed && row.list_id === state.lists.find(list => list.name === 'Ziel')?.id && row.completed_expires_at !== null
    }).toBe(true)
  })

  test('Listen- und Gesamteinstellungen geben nach dem Breitenwechsel den Fokus zurück', async ({ page }) => {
    await (mobile ? phone.register : desktop.register)(page, desktop.uniqueEmail('ui-settings-focus'))
    await (mobile ? phone.createList : desktop.createList)(page, 'Arbeit')
    const settings = await desktop.openListSettings(page)
    await page.setViewportSize(mobile ? { width: 1280, height: 800 } : { width: 390, height: 844 })
    await settings.getByRole('button', { name: 'Schließen', exact: true }).click()
    await expect(page.locator('[data-focus-key^="settings:list:"]')).toBeFocused()
    await openOverview(page, !mobile)
    const overall = await overviewSettings(page)
    await page.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1280, height: 800 })
    await overall.getByRole('button', { name: 'Schließen', exact: true }).click()
    await expect(page.locator('[data-focus-key="settings:overview"]')).toBeFocused()
  })

  test('der Editor bleibt bei 200 Prozent Schrift bedienbar', async ({ page }, info) => {
    await (mobile ? phone.register : desktop.register)(page, desktop.uniqueEmail('ui-large-text'))
    await (mobile ? phone.createList : desktop.createList)(page, 'Arbeit')
    await (mobile ? phone.createTask : desktop.createTask)(page, 'Vergrößerte Schrift')
    const editor = await desktop.openTaskEditor(page, 'Vergrößerte Schrift')
    await page.evaluate(() => { document.documentElement.style.fontSize = '200%' })
    await editor.getByLabel('Beschreibung (optional)').fill('Auch mit vergrößerter Schrift gespeichert.')
    await expect(editor.getByRole('button', { name: 'Speichern', exact: true })).toBeInViewport()
    await page.screenshot({ path: info.outputPath(mobile ? 'editor-large-text-phone.png' : 'editor-large-text-desktop.png') })
    const overflow = await editor.evaluate(node => {
      const right = node.getBoundingClientRect().right
      return [...node.querySelectorAll<HTMLElement>('*')].filter(child => child.getBoundingClientRect().right > right + 1)
        .map(child => ({ tag: child.tagName, label: child.getAttribute('aria-label') ?? child.textContent?.slice(0, 50), width: child.getBoundingClientRect().width }))
    })
    await info.attach('horizontal-overflow', { body: JSON.stringify(overflow), contentType: 'application/json' })
    expect(await editor.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await editor.getByRole('button', { name: 'Speichern', exact: true }).click()
    await expect(editor).toBeHidden()
    await expect(page.getByText('Auch mit vergrößerter Schrift gespeichert.', { exact: true })).toBeVisible()
  })

  test('Listenverwaltung und Gesamtansicht bilden denselben Kernablauf', async ({ page }, info) => {
    await (mobile ? phone.register : desktop.register)(page, desktop.uniqueEmail('ui-view'))
    await (mobile ? phone.createList : desktop.createList)(page, 'Privat')
    await (mobile ? phone.createTask : desktop.createTask)(page, 'Den nächsten Urlaub planen und die passende Verbindung heraussuchen')
    const settings = await desktop.openListSettings(page)
    await expect(settings.getByLabel('In Gesamtansicht aufnehmen')).not.toBeChecked()
    await expect(settings.getByLabel('Abgehakt am Listenende')).not.toBeChecked()
    await settings.getByLabel('In Gesamtansicht aufnehmen').check()
    await settings.getByLabel('Abgehakt am Listenende').check()
    await page.screenshot({ path: info.outputPath(mobile ? 'settings-phone.png' : 'settings-desktop.png') })
    await desktop.closeListSettings(page)
    await openOverview(page, mobile)
    await expect(page.getByTestId('overview-task')).toContainText('Den nächsten Urlaub planen')
    await page.screenshot({ path: info.outputPath(mobile ? 'overview-phone.png' : 'overview-desktop.png') })
    if (mobile) {
      await page.setViewportSize({ width: 740, height: 360 })
      await page.screenshot({ path: info.outputPath('overview-landscape.png') })
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const overall = await overviewSettings(page)
    await expect(overall.getByLabel('Privat', { exact: true })).toBeChecked()
  })
})

test('Aufgaben bleiben in kurzen breiten Fenstern erreichbar', async ({ page }, info) => {
  await desktop.resetServer(page.request)
  await desktop.register(page, desktop.uniqueEmail('ui-short-height'))
  await desktop.createList(page, 'Arbeit')
  await desktop.createTask(page, 'Auch im Querformat erreichbar')
  for (const width of [844, 1280]) {
    await page.setViewportSize({ width, height: 390 })
    const item = desktop.taskItem(page, 'Auch im Querformat erreichbar').getByRole('button', { name: 'Bearbeiten', exact: true })
    await item.scrollIntoViewIfNeeded()
    await expect(item).toBeInViewport()
    await page.screenshot({ path: info.outputPath(`list-short-${width}.png`) })
    await item.click()
    const editor = page.getByRole('dialog', { name: 'Aufgabe', exact: true })
    await expect(editor.getByLabel('Titel', { exact: true })).toHaveValue('Auch im Querformat erreichbar')
    await editor.getByRole('button', { name: 'Schließen', exact: true }).click()
  }
})
