import { afterEach, describe, expect, it } from 'vitest'
import { FakeServer } from '../support/fakeGateway'
import { createDevice, type DeviceHarness } from '../support/harness'
import { createFixedClock, localTask, T0 } from '../support/factories'
import { normalisiereAufgabe } from '../../src/domain/normalize'

const DAY = 86400000
const devices: DeviceHarness[] = []
afterEach(async () => { await Promise.all(devices.splice(0).map(device => device.dispose())) })
async function setup(server = new FakeServer(createFixedClock()), userId = 'owner') {
  const device = await createDevice({ userId, gateway: server.gatewayFor(userId), clock: server.clock as ReturnType<typeof createFixedClock> })
  devices.push(device)
  return { device, server, list: await device.repositories.createList('Liste', userId) }
}
describe('Abgehakt, Fristen und Rückkehr', () => {
  it.each(['bearbeitet','verschoben','umsortiert'] as const)('behält einen inzwischen %s nächsten Termin auch bei gleicher Millisekunde', async change => {
    const { device, list } = await setup()
    const original = await device.repositories.createTask({listId:list.id,title:'Serie',dueAt:'2026-01-01T12:00:00.000Z',recurrence:'daily'})
    const completed = await device.repositories.setTaskCompleted(original.id,true)
    const nextId = completed.successor_id!
    if (change === 'bearbeitet') await device.repositories.updateTask(nextId,{title:'Bewusst geändert'})
    if (change === 'verschoben') {
      const target=await device.repositories.createList('Ziel','owner')
      await device.repositories.moveTask(nextId,target.id)
    }
    if (change === 'umsortiert') await device.repositories.reorderTasks(list.id,[nextId])
    const before=await device.repositories.getTask(nextId)
    const reopened=await device.repositories.setTaskCompleted(original.id,false)
    expect(reopened.completed).toBe(false)
    expect(reopened.successor_id).toBeNull()
    expect(await device.repositories.getTask(nextId)).toEqual(before)
  })
  it('behält den nächsten Termin bei alten Abschlüssen ohne gesicherten Ausgangsstand', async () => {
    const { device, list }=await setup()
    const original=await device.repositories.createTask({listId:list.id,title:'Altserie',dueAt:'2026-01-01T12:00:00.000Z',recurrence:'daily'})
    const completed=await device.repositories.setTaskCompleted(original.id,true)
    await device.db.tasks.update(original.id,{reopen_context:null})
    await device.repositories.setTaskCompleted(original.id,false)
    expect(await device.repositories.getTask(completed.successor_id!)).toBeDefined()
  })
  it('nimmt unveränderte nächste Termine auch nach erneutem Abhaken zurück', async () => {
    const { device, list }=await setup()
    const original=await device.repositories.createTask({listId:list.id,title:'Serie',dueAt:'2026-01-01T12:00:00.000Z',recurrence:'daily'})
    const first=await device.repositories.setTaskCompleted(original.id,true)
    const created=(await device.repositories.getTask(first.successor_id!))!.created_at
    await device.repositories.setTaskCompleted(original.id,false)
    expect(await device.repositories.getTask(first.successor_id!)).toBeUndefined()
    device.clock.advance(60000)
    const second=await device.repositories.setTaskCompleted(original.id,true)
    expect(second.successor_id).toBe(first.successor_id)
    expect((await device.repositories.getTask(second.successor_id!))?.created_at).toBe(created)
    await device.repositories.setTaskCompleted(original.id,false)
    expect(await device.repositories.getTask(second.successor_id!)).toBeUndefined()
  })
  it('ist zunächst aus; an bleibt ein Abschluss dauerhaft ausschließlich am Listenende', async () => {
    const { device, list } = await setup()
    expect(list.keep_completed).toBe(false)
    await device.repositories.setListKeepCompleted(list.id, 'owner', true)
    const task = await device.repositories.createTask({ listId: list.id, title: 'Alt' })
    await device.repositories.setTaskCompleted(task.id, true)
    device.clock.advance(40 * DAY)
    expect(await device.repositories.listCompletedTasks(list.id)).toHaveLength(1)
    expect(await device.repositories.listRestorableTasks()).toEqual([])
    await expect(device.repositories.setListKeepCompleted(list.id, 'member', false)).rejects.toThrow('Besitzer')
  })
  it('gewährt beim Abschalten sieben Tage, bewahrt den Zeitpunkt und verhindert Wiederbelebung', async () => {
    const { device, list } = await setup()
    await device.repositories.setListKeepCompleted(list.id, 'owner', true)
    const task = await device.repositories.createTask({ listId: list.id, title: 'Abschluss' })
    const completed = await device.repositories.setTaskCompleted(task.id, true)
    device.clock.advance(30 * DAY)
    await device.repositories.setListKeepCompleted(list.id, 'owner', false)
    const stored = await device.repositories.getTask(task.id)
    expect(stored?.completed_at).toBe(completed.completed_at)
    expect(await device.repositories.listRestorableTasks()).toHaveLength(1)
    device.clock.advance(7 * DAY)
    await expect(device.repositories.setTaskCompleted(task.id, false)).rejects.toThrow('abgelaufen')
    await expect(device.repositories.restoreTask(task.id)).rejects.toThrow('abgelaufen')
    await device.repositories.setListKeepCompleted(list.id, 'owner', true)
    expect(await device.repositories.listCompletedTasks(list.id)).toEqual([])
    expect(await device.repositories.listDeletedTasks()).toEqual([])
  })
  it('öffnet neben dem Vorgänger, sonst Nachfolger, ohne Ankern in fremde Gruppen zu folgen', async () => {
    const { device, list } = await setup()
    const g = await device.repositories.addListSection(list.id, 'Gruppe')
    const a = await device.repositories.createTask({ listId: list.id, sectionId: g, title: 'A' })
    const b = await device.repositories.createTask({ listId: list.id, sectionId: g, title: 'B' })
    const c = await device.repositories.createTask({ listId: list.id, sectionId: g, title: 'C' })
    await device.repositories.reorderTasks(list.id, [a.id,b.id,c.id])
    await device.repositories.setTaskCompleted(b.id, true)
    await device.repositories.reorderTasks(list.id, [c.id,a.id])
    await device.repositories.setTaskCompleted(b.id, false)
    expect((await device.repositories.listTasks(list.id)).map(task => task.title)).toEqual(['C','A','B'])
    await device.repositories.reorderTasks(list.id, [a.id,b.id,c.id])
    await device.repositories.setTaskCompleted(b.id, true)
    await device.repositories.moveTask(a.id, list.id, null)
    await device.repositories.setTaskCompleted(b.id, false)
    const peers=(await device.repositories.listTasks(list.id)).filter(task => task.section_id === g)
    expect(peers.map(task => task.title)).toEqual(['B','C'])
    await device.repositories.setTaskCompleted(b.id, true)
    await device.repositories.deleteListSection(list.id,g!)
    expect((await device.repositories.setTaskCompleted(b.id,false)).section_id).toBeNull()
  })
  it('wendet beim Verschieben die Zielliste an, ohne den Abschlusszeitpunkt zu ändern', async () => {
    const { device, list } = await setup()
    const target = await device.repositories.createList('Ziel', 'owner')
    await device.repositories.setListKeepCompleted(list.id, 'owner', true)
    const task = await device.repositories.createTask({ listId:list.id,title:'Verschieben' })
    const completed = await device.repositories.setTaskCompleted(task.id,true)
    device.clock.advance(20*DAY)
    const moved=await device.repositories.moveTask(task.id,target.id)
    expect(moved.completed_at).toBe(completed.completed_at)
    expect(Date.parse(moved.completed_expires_at!)-device.clock.nowMs()).toBe(7*DAY)
    await device.repositories.moveTask(task.id,list.id)
    expect((await device.repositories.getTask(task.id))?.completed_expires_at).toBeNull()
  })
  it('ordnet bei erschöpftem Positionsabstand nur die ursprüngliche Gruppe neu', async () => {
    const { device, list } = await setup()
    const g = await device.repositories.addListSection(list.id, 'Gruppe')
    const a = await device.repositories.createTask({listId:list.id,sectionId:g,title:'A'})
    const b = await device.repositories.createTask({listId:list.id,sectionId:g,title:'B'})
    const c = await device.repositories.createTask({listId:list.id,sectionId:g,title:'C'})
    const outside = await device.repositories.createTask({listId:list.id,title:'Außerhalb'})
    await device.repositories.reorderTasks(list.id,[a.id,b.id,c.id,outside.id])
    await device.repositories.setTaskCompleted(b.id,true)
    await device.db.tasks.update(a.id,{position:1})
    await device.db.tasks.update(c.id,{position:1+Number.EPSILON})
    await device.db.tasks.update(outside.id,{dirty:0})
    const before=await device.db.tasks.get(outside.id)
    await device.repositories.setTaskCompleted(b.id,false)
    expect((await device.repositories.listTasks(list.id)).filter(task=>task.section_id===g).map(task=>task.title)).toEqual(['A','B','C'])
    expect(await device.db.tasks.get(outside.id)).toEqual(before)
  })
  it('übernimmt bestätigte Serverfristen trotz abweichender Geräteuhr ohne Benutzerkonflikt', async () => {
    const serverClock=createFixedClock(Date.parse(T0)+5*60000)
    const server=new FakeServer(serverClock)
    const device=await createDevice({userId:'owner',gateway:server.gatewayFor('owner'),clock:createFixedClock(Date.parse(T0))})
    devices.push(device)
    const list=await device.repositories.createList('Liste','owner')
    await device.repositories.setListKeepCompleted(list.id,'owner',true)
    const task=await device.repositories.createTask({listId:list.id,title:'Bleibt erhalten'})
    await device.repositories.setTaskCompleted(task.id,true)
    await device.engine.sync()
    device.clock.advance(20*DAY)
    serverClock.advance(20*DAY)
    await device.repositories.setListKeepCompleted(list.id,'owner',false)
    await device.engine.sync()
    expect(await device.repositories.listCloudConflicts()).toEqual([])
    expect((await device.repositories.getList(list.id))?.keep_completed).toBe(false)
    expect((await device.db.lists.get(list.id))?.dirty).toBe(0)
    expect((await device.db.tasks.get(task.id))?.dirty).toBe(0)
    expect(Date.parse((await device.repositories.getTask(task.id))!.completed_expires_at!)-server.clock.nowMs()).toBe(7*DAY)
  })
  it('nimmt den Serverablauf gegen verspätete Offline-Bearbeitung an; keine Konfliktwahl stellt ihn wieder her', async () => {
    const { device, server, list } = await setup()
    const task = await device.repositories.createTask({ listId:list.id,title:'Endgültig' })
    await device.repositories.setTaskCompleted(task.id,true)
    await device.engine.sync()
    const stale={...normalisiereAufgabe((await device.db.tasks.get(task.id))!),completed:false,completed_at:null,completed_expires_at:null,dirty:1 as const}
    device.clock.advance(8*DAY)
    server.expireCompleted()
    await device.db.tasks.put(stale)
    await device.engine.sync()
    expect(await device.repositories.getTask(task.id)).toBeUndefined()
    expect((await device.db.tasks.get(task.id))?.expired_at).not.toBeNull()
    expect(await device.repositories.listCloudConflicts()).toEqual([])
    expect(await device.repositories.listDeletedTasks()).toEqual([])
  })
  it('bewahrt ungesendete alte Abschlüsse nach dem Abschalten auf einem anderen Gerät', async () => {
    const { device, server, list } = await setup()
    await device.repositories.setListKeepCompleted(list.id,'owner',true)
    await device.engine.sync()
    device.clock.advance(20*DAY)
    const cloudList=server.lists.get(list.id)!
    await server.gatewayFor('owner').push({lists:[{...cloudList,keep_completed:false}],members:[],tasks:[]},{lists:{[list.id]:cloudList}})
    const offline = localTask({id:'offline',list_id:list.id,completed:true,completed_at:'2026-01-02T00:00:00.000Z',dirty:1})
    await device.db.tasks.put(offline)
    await device.engine.sync()
    expect(await device.repositories.listRestorableTasks()).toHaveLength(1)
    expect(Date.parse((await device.repositories.getTask('offline'))!.completed_expires_at!)-server.clock.nowMs()).toBe(7*DAY)
  })
})
